name: Update news data

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:      # allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow committing the updated JSON
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 lxml requests

      - name: Update combined_news.json
        run: python scripts/update_news.py

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/combined_news.json
            git commit -m "chore: refresh news data [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
