name: Update news data

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

permissions:
  contents: write   # allow committing & pushing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, keep credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 lxml requests

      - name: Update JSONs
        run: python scripts/update_news.py

      # Commit to data-updates branch
      - name: Commit & push data files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "chore: refresh news + constituency summary [skip ci]"
            branch: data-updates
            create_branch: true
            file_pattern: |
              data/combined_news.json
              data/constituency_rank.json
